In [57]:
import pandas as pd
import numpy as np
import pickle

In [6]:
import psycopg2
import pandas.io.sql as psql

from pybaseball import playerid_lookup

In [3]:
conn = psycopg2.connect(dbname='pitches_2018', user='taylorphillips', host='localhost')

In [5]:
cur = conn.cursor()

In [47]:
test = psql.read_sql('''
SELECT player_name, pitch_type, game_date, AVG(release_speed) as release_speed, AVG(release_pos_x) as avg_x, AVG(release_pos_y) as avg_y, AVG(release_pos_z) as avg_z, pitcher FROM pitches 
WHERE pitcher = 434378
GROUP BY pitch_type, game_date, pitcher, player_name
ORDER BY game_date
''', conn)

In [8]:
playerid_lookup('verlander')

Gathering player lookup table. This may take a moment.

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,verlander,ben,595449,NaN,NaN,-1,NaN,NaN
1,verlander,justin,434378,verlj001,verlaju01,8700,2005.0,2019.0

In [18]:
test['index'].values

array([   0,    1,    2, ..., 3713, 3714, 3715])

In [48]:
pd.set_option('display.max_columns', 500)
test

,player_name,pitch_type,game_date,release_speed,avg_x,avg_y,avg_z,pitcher
0,Justin Verlander,CU,2018-03-29,79.284615,-2.194362,55.507754,6.575177,434378.0
1,Justin Verlander,FC,2018-03-29,92.500000,-2.064800,54.460500,6.666700,434378.0
2,Justin Verlander,FF,2018-03-29,94.996296,-1.948019,54.621581,6.739111,434378.0
3,Justin Verlander,SL,2018-03-29,86.590000,-2.220130,54.895985,6.521870,434378.0
4,Justin Verlander,CH,2018-04-03,87.100000,-2.088600,53.374600,6.474500,434378.0
5,Justin Verlander,CU,2018-04-03,78.807692,-2.078100,55.118323,6.584123,434378.0
6,Justin Verlander,FF,2018-04-03,94.473684,-1.911333,54.510432,6.736032,434378.0
7,Justin Verlander,SL,2018-04-03,85.690625,-2.181313,54.658984,6.510847,434378.0
8,Justin Verlander,CH,2018-04-09,87.250000,-1.999600,54.636800,6.606150,434378.0
9,Justin Verlander,CU,2018-04-09,78.600000,-2.162486,54.855300,6.520786,434378.0
10,Justin Verlander,FC,2018-04-09,90.400000,-2.099800,54.114900,6.511600,434378.0
11,Justin Verlander,FF,2018-04-09,94.107246,-1.919343,54.525641,6.691883,434378.0
12,Justin Verlander,SL,2018-04-09,86.156667,-2.212177,54.631427,6.490257,434378.0
13,Justin Verlander,CH,2018-04-15,86.200000,-2.233600,54.521400,6.602300,434378.0
14,Justin Verlander,CU,2018-04-15,80.014286,-2.055221,54.878114,6.634036,434378.0
15,Justin Verlander,FF,2018-04-15,94.353030,-1.876906,54.537042,6.782189,434378.0
16,Justin Verlander,SL,2018-04-15,87.389474,-2.182032,54.608584,6.529453,434378.0
17,Justin Verlander,CH,2018-04-20,86.420000,-2.178580,54.462560,6.516860,434378.0
18,Justin Verlander,CU,2018-04-20,80.500000,-2.076122,55.035189,6.525956,434378.0
19,Justin Verlander,FF,2018-04-20,93.883871,-1.849566,54.441940,6.751703,434378.0
20,Justin Verlander,SL,2018-04-20,86.860000,-2.120230,54.717910,6.560620,434378.0
21,Justin Verlander,CH,2018-04-25,88.650000,-2.216900,54.309900,6.465200,434378.0
22,Justin Verlander,CU,2018-04-25,80.516667,-2.047792,55.106100,6.654417,434378.0
23,Justin Verlander,FC,2018-04-25,91.420000,-2.149440,54.353860,6.602660,434378.0
24,Justin Verlander,FF,2018-04-25,95.869697,-1.804253,54.489802,6.786315,434378.0
25,Justin Verlander,SL,2018-04-25,87.833333,-2.103008,54.568042,6.563550,434378.0
26,Justin Verlander,CU,2018-05-01,80.200000,-2.115228,54.971528,6.545322,434378.0
27,Justin Verlander,FF,2018-05-01,95.396491,-1.866958,54.424263,6.747172,434378.0
28,Justin Verlander,SL,2018-05-01,87.210000,-2.206140,54.583103,6.501607,434378.0
29,Justin Verlander,CH,2018-05-06,89.100000,-2.216500,54.856800,6.395000,434378.0
...,...,...,...,...,...,...,...,...
121,Justin Verlander,SL,2018-08-30,84.942105,-2.178458,54.858058,6.658653,434378.0
122,Justin Verlander,CH,2018-09-04,88.466667,-2.141200,54.225300,6.610267,434378.0
123,Justin Verlander,CU,2018-09-04,78.892308,-2.070408,55.528527,6.713488,434378.0
124,Justin Verlander,FF,2018-09-04,94.460000,-1.883094,54.702236,6.902632,434378.0
125,Justin Verlander,SL,2018-09-04,87.404348,-2.220387,54.764448,6.605191,434378.0
126,Justin Verlander,CH,2018-09-10,87.933333,-2.165167,54.316867,6.759700,434378.0
127,Justin Verlander,CU,2018-09-10,80.350000,-2.046300,55.480383,6.797733,434378.0
128,Justin Verlander,FF,2018-09-10,95.402083,-1.808337,54.655723,7.003592,434378.0
129,Justin Verlander,SL,2018-09-10,87.753125,-2.139063,54.916344,6.782519,434378.0
130,Justin Verlander,CH,2018-09-16,87.700000,-2.020700,54.345900,6.624500,434378.0
131,Justin Verlander,CU,2018-09-16,79.685714,-1.920907,55.328486,6.719007,434378.0
132,Justin Verlander,FF,2018-09-16,94.689394,-1.675979,54.573944,6.974898,434378.0
133,Justin Verlander,SL,2018-09-16,88.165000,-1.981145,54.681695,6.714015,434378.0
134,Justin Verlander,CU,2018-09-22,79.729412,-1.920982,55.448347,6.726976,434378.0
135,Justin Verlander,FF,2018-09-22,95.144615,-1.638351,54.499026,6.966840,434378.0
136,Justin Verlander,SL,2018-09-22,88.095238,-1.964090,54.633610,6.722352,434378.0
137,Justin Verlander,CU,2018-09-29,80.633333,-1.885300,55.537156,6.758167,434378.0
138,Justin Verlander,FF,2018-09-29,95.518519,-1.642348,54.686778,7.005087,434378.0
139,Justin Verlander,SL,2018-09-29,88.148148,-1.948556,54.849570,6.743293,434378.0
140,Justin Verlander,CH,2018-10-05,89.400000,-2.086600,54.347400,6.552300,434378.0
141,Justin Verlander,CU,2018-10-05,81.376923,-1.992438,55.072592,6.661408,434378.0
142,Justin Verlander,FF,2018-10-05,96.211111,-1.700830,54.517449,6.896956,434378.0
143,Justin Verlander,SL,2018-10-05,89.148000,-2.054352,54.588828,6.620396,434378.0
144,Justin Verlander,CU,2018-10-13,81.350000,-1.883906,54.989300,6.605394,434378.0
145,Justin Verlander,FF,2018-10-13,96.232787,-1.570772,54.544610,6.816874,434378.0
146,Justin Verlander,SL,2018-10-13,89.963636,-1.899164,54.678855,6.587236,434378.0
147,Justin Verlander,CH,2018-10-18,88.400000,-2.059600,54.340100,6.742300,434378.0
148,Justin Verlander,CU,2018-10-18,80.342105,-1.937753,55.145126,6.751716,434378.0
149,Justin Verlander,FF,2018-10-18,95.805085,-1.641098,54.584510,6.960056,434378.0
150,Justin Verlander,SL,2018-10-18,88.488889,-1.999533,54.709983,6.726661,434378.0

In [34]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3716 entries, 0 to 3715
Data columns (total 8 columns):
pitch_type       3712 non-null object
game_date        3716 non-null object
release_speed    3713 non-null float64
release_pos_x    3710 non-null float64
release_pos_y    3710 non-null float64
release_pos_z    3710 non-null float64
player_name      3716 non-null object
pitcher          3716 non-null float64
dtypes: float64(5), object(3)
memory usage: 232.3+ KB

In [31]:
pitch_type, game_date, release_speed, release_pos_x, release_pos_y, release_pos_z, player_name, pitcher

NameError: name 'pitch_type' is not defined

In [52]:
season = psql.read_sql('''
SELECT player_name, pitch_type, count(pitch_type) as count, AVG(release_speed) as release_speed, AVG(release_pos_x) as avg_x, AVG(release_pos_y) as avg_y, AVG(release_pos_z) as avg_z, pitcher FROM pitches 
WHERE pitcher = 434378
GROUP BY pitch_type, pitcher, player_name
''', conn)

In [53]:
season

,player_name,pitch_type,count,release_speed,avg_x,avg_y,avg_z,pitcher
0,Justin Verlander,CH,53,87.430189,-2.187598,54.443113,6.625634,434378.0
1,Justin Verlander,CU,545,79.682202,-2.072916,55.280479,6.688882,434378.0
2,Justin Verlander,FC,20,91.515000,-2.131005,54.547575,6.665945,434378.0
3,Justin Verlander,FF,2277,95.112912,-1.826646,54.562307,6.866587,434378.0
4,Justin Verlander,SL,817,86.656304,-2.162997,54.758830,6.613994,434378.0
5,Justin Verlander,None,0,73.700000,NaN,NaN,NaN,434378.0

In [54]:
average_player = psql.read_sql('''
SELECT pitch_type, count(pitch_type) as count, AVG(release_speed) as release_speed, AVG(release_pos_x) as avg_x, AVG(release_pos_y) as avg_y, AVG(release_pos_z) as avg_z FROM pitches 
GROUP BY pitch_type
''', conn)

In [55]:
average_player

   pitch_type   count  release_speed     avg_x      avg_y     avg_z
0          CH   75269      84.218852 -0.492560  54.431169  5.814540
1          CU   60997      78.274018 -0.598007  54.845546  5.946622
2          EP     205      67.587317 -1.717004  54.559287  6.097878
3          FC   40311      88.695800 -0.493349  54.557862  5.873192
4          FF  257624      93.186497 -0.843555  54.345826  5.906338
5          FO      84      86.336905 -1.930927  55.372314  6.260949
6          FS   10534      85.154262 -1.205614  54.723958  5.985532
7          FT   81309      92.485803 -0.873533  54.450194  5.909269
8          KC   16812      80.983036 -1.023259  54.807663  5.893546
9          KN     719      75.931293 -0.776325  54.709983  5.776621
10         PO      89      88.144944 -1.795900  54.545284  5.887682
11         SC      37      77.494595  2.408589  55.038392  5.776116
12         SI   58851      91.601580 -0.317662  54.438605  5.633005
13         SL  123614      84.394497 -0.978432  54.718031  5.832062
14       None       0      77.298039 -1.337431  54.398877  6.043477

In [56]:
average_player.sum()

count            726455.000000
release_speed      1251.787440
avg_x               -11.974969
avg_y               819.942992
avg_z                88.636829
dtype: float64

In [58]:
errors = pd.read_pickle('errors.pkl')

In [59]:
len(errors)

3697

In [61]:
b= psql.read_sql('''
SELECT * from pitches
ORDER BY pitcher, game_date
''', conn)

In [62]:
len(b)

730136

In [63]:
len(b) - len(errors)

726439