In [8]:
import pandas as pd
import numpy as np
import pickle
pd.set_option('display.max_columns', 500)
from pybaseball import *

In [2]:
pwd

'/Users/taylorphillips/galvanize/mlb/mlb_injuries/notebooks'

In [95]:
games = pd.read_pickle('../pickles/2018_games.pkl')

In [12]:
# jv = games[games['Name'] == 'Justin Verlander']

In [34]:
# games['date'] = pd.to_datetime(games['date'], format="%Y/%m/%d")

In [36]:
games.columns = [x.lower().strip() for x in games.columns]

In [38]:
# games = games.set_index(np.arange(len(games)))

In [99]:
games[games['name'] == 'Charlie Morton']

,name,age,#days,lev,tm,g,gs,w,l,sv,ip,h,r,er,bb,so,hr,hbp,era,ab,2b,3b,ibb,gdp,sf,sb,cs,po,bf,pit,str,stl,sts,gb/fb,ld,pu,whip,babip,so9,so/w,date
529,Charlie Morton,34,364,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,3,0,0,2,6,0,1,0.00,21,1,0,0,0,0,0,0,0,24,91,0.62,0.16,0.19,0.60,0.27,0.00,0.833,0.200,9.0,3.00,2018-04-02
1195,Charlie Morton,34,358,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,4,1,0,3,7,0,1,0.00,23,0,0,0,0,0,1,0,0,27,101,0.66,0.19,0.15,0.69,0.13,0.13,1.167,0.250,10.5,2.33,2018-04-08
1859,Charlie Morton,34,352,MLB-AL,Houston,1,1,NaN,NaN,NaN,6.0,6,2,2,1,12,2,0,3.00,23,0,0,0,1,0,0,0,0,24,106,0.64,0.22,0.16,0.45,0.27,0.09,1.167,0.444,18.0,12.00,2018-04-14
2351,Charlie Morton,34,347,MLB-AL,Houston,1,1,1.0,NaN,NaN,7.0,3,0,0,0,8,0,0,0.00,24,0,0,0,0,0,0,0,0,24,86,0.69,0.16,0.13,0.63,0.13,0.00,0.429,0.188,10.3,NaN,2018-04-19
2883,Charlie Morton,34,342,MLB-AL,Houston,1,1,NaN,NaN,NaN,4.0,5,4,4,5,2,2,0,9.00,15,0,0,0,2,0,1,0,0,20,75,0.59,0.25,0.05,0.54,0.15,0.15,2.500,0.273,4.5,0.40,2018-04-24
3598,Charlie Morton,34,336,MLB-AL,Houston,1,1,1.0,NaN,NaN,7.2,2,1,1,2,10,0,0,1.17,24,1,0,0,1,0,0,0,0,26,102,0.66,0.20,0.13,0.62,0.15,0.15,0.522,0.143,11.7,5.00,2018-04-30
4179,Charlie Morton,34,331,MLB-AL,Houston,1,1,NaN,NaN,NaN,5.0,3,3,3,4,3,1,1,5.40,16,1,0,0,0,1,0,0,0,22,82,0.52,0.17,0.05,0.47,0.20,0.07,1.400,0.154,5.4,0.75,2018-05-05
4959,Charlie Morton,34,324,MLB-AL,Houston,1,1,1.0,NaN,NaN,7.0,4,1,1,0,14,1,0,1.29,25,2,0,0,0,0,0,0,0,25,105,0.63,0.18,0.20,0.73,0.18,0.00,0.571,0.300,18.0,NaN,2018-05-12
5577,Charlie Morton,34,318,MLB-AL,Houston,1,1,1.0,NaN,NaN,7.0,4,1,1,1,8,1,0,1.29,25,0,0,0,0,0,0,0,0,26,97,0.69,0.20,0.09,0.47,0.12,0.12,0.714,0.188,10.3,8.00,2018-05-18
6220,Charlie Morton,34,312,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,5,2,2,3,5,0,0,3.00,21,1,0,0,1,0,0,0,0,24,92,0.64,0.17,0.10,0.56,0.25,0.00,1.333,0.313,7.5,1.67,2018-05-24
6848,Charlie Morton,34,307,MLB-AL,Houston,1,1,NaN,NaN,NaN,6.0,8,3,3,1,10,2,0,4.50,26,2,0,0,0,0,0,0,0,27,100,0.66,0.25,0.09,0.44,0.25,0.06,1.500,0.429,15.0,10.00,2018-05-29
7414,Charlie Morton,34,302,MLB-AL,Houston,1,1,NaN,1.0,NaN,5.1,9,6,6,1,7,2,1,10.13,24,2,1,0,0,0,0,0,0,26,100,0.63,0.17,0.10,0.35,0.35,0.06,1.875,0.467,11.8,7.00,2018-06-03
8049,Charlie Morton,34,296,MLB-AL,Houston,1,1,NaN,NaN,NaN,3.2,1,2,1,6,4,0,4,2.45,12,1,0,0,0,1,0,0,0,23,87,0.54,0.18,0.07,0.33,0.56,0.00,1.909,0.111,9.8,0.67,2018-06-09
8678,Charlie Morton,34,290,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,4,3,3,4,9,0,0,4.50,21,1,0,0,1,0,0,0,0,25,98,0.66,0.20,0.16,0.58,0.17,0.08,1.333,0.333,13.5,2.25,2018-06-15
9260,Charlie Morton,34,285,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,2,1,0,4,4,0,1,0.00,20,1,0,0,0,0,0,0,0,25,96,0.64,0.14,0.15,0.59,0.24,0.06,1.000,0.125,6.0,1.00,2018-06-20
9953,Charlie Morton,34,279,MLB-AL,Houston,1,1,1.0,NaN,NaN,7.0,4,0,0,2,13,0,0,0.00,24,0,0,0,0,0,0,1,0,26,98,0.68,0.14,0.23,0.45,0.36,0.00,0.857,0.364,16.7,6.50,2018-06-26
10522,Charlie Morton,34,274,MLB-AL,Houston,1,1,NaN,1.0,NaN,6.2,6,2,2,2,11,0,1,2.70,25,0,0,0,0,0,0,0,0,28,103,0.65,0.18,0.15,0.36,0.50,0.00,1.200,0.429,14.9,5.50,2018-07-01
11171,Charlie Morton,34,268,MLB-AL,Houston,1,1,1.0,NaN,NaN,5.2,5,5,5,2,8,0,0,7.94,22,2,0,0,0,1,1,0,0,25,101,0.65,0.21,0.12,0.40,0.27,0.07,1.235,0.333,12.7,4.00,2018-07-07
11772,Charlie Morton,34,263,MLB-AL,Houston,1,1,NaN,NaN,NaN,4.1,6,3,3,2,5,0,0,6.23,19,2,0,0,0,0,0,0,0,21,104,0.63,0.21,0.08,0.36,0.36,0.07,1.846,0.429,10.4,2.50,2018-07-12
12947,Charlie Morton,34,250,MLB-AL,Houston,1,1,NaN,NaN,NaN,6.0,4,1,1,4,5,1,1,1.50,20,1,0,0,0,0,0,1,0,25,102,0.57,0.10,0.14,0.67,0.27,0.00,1.333,0.214,7.5,1.25,2018-07-25
13611,Charlie Morton,34,244,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,6,2,2,1,8,1,0,3.00,23,0,1,0,0,0,0,0,0,24,86,0.64,0.22,0.14,0.53,0.33,0.00,1.167,0.357,12.0,8.00,2018-07-31
14281,Charlie Morton,34,238,MLB-AL,Houston,1,1,NaN,NaN,NaN,7.0,3,1,1,3,8,1,0,1.29,22,1,0,0,1,0,0,0,0,26,97,0.66,0.27,0.11,0.29,0.21,0.07,0.857,0.154,10.3,2.67,2018-08-06
14839,Charlie Morton,34,233,MLB-AL,Houston,1,1,NaN,1.0,NaN,6.0,7,3,3,1,4,0,1,4.50,21,2,1,0,3,0,0,0,0,23,87,0.59,0.16,0.09,0.61,0.28,0.00,1.333,0.412,6.0,4.00,2018-08-11
15514,Charlie Morton,34,227,MLB-AL,Houston,1,1,NaN,NaN,NaN,5.0,4,2,0,2,4,0,0,0.00,19,1,0,0,1,0,0,0,0,21,86,0.65,0.14,0.07,0.27,0.20,0.13,1.200,0.267,7.2,2.00,2018-08-17
16111,Charlie Morton,34,222,MLB-AL,Houston,1,1,1.0,NaN,NaN,5.0,7,6,6,1,7,1,2,10.80,22,3,0,0,0,0,0,0,0,25,91,0.65,0.21,0.07,0.47,0.20,0.13,1.600,0.429,12.6,7.00,2018-08-22
16764,Charlie Morton,34,216,MLB-AL,Houston,1,1,NaN,NaN,NaN,4.2,3,3,3,4,3,1,1,5.79,17,0,0,0,0,0,1,0,0,22,89,0.60,0.16,0.09,0.50,0.14,0.00,1.500,0.154,5.8,0.75,2018-08-28
18127,Charlie Morton,34,205,MLB-AL,Houston,1,1,1.0,NaN,NaN,5.0,7,2,2,2,3,1,0,3.60,22,1,0,0,0,0,0,0,0,24,94,0.64,0.19,0.05,0.37,0.32,0.00,1.800,0.333,5.4,1.50,2018-09-08
19030,Charlie Morton,34,198,MLB-AL,Houston,1,1,1.0,NaN,NaN,6.0,3,2,2,0,7,1,1,3.00,20,0,0,0,0,1,0,0,0,23,70,0.79,0.30,0.10,0.29,0.36,0.07,0.500,0.154,10.5,NaN,2018-09-15
20097,Charlie Morton,34,190,MLB-AL,Houston,1,1,NaN,NaN,NaN,1.0,1,1,1,0,2,0,0,9.00,4,1,0,0,0,0,0,0,0,4,24,0.63,0.13,0.17,0.50,0.50,0.00,1.000,0.500,18.0,NaN,2018-09-23
21095,Charlie Morton,34,183,MLB-AL,Houston,1,1,NaN,NaN,NaN,3.0,1,0,0,1,4,0,0,0.00,9,0,0,0,1,0,0,0,0,10,34,0.56,0.15,0.18,0.50,0.50,0.00,0.667,0.200,12.0,4.00,2018-09-30

In [123]:
dl_18 = pd.read_pickle('../pickles/2018_DL.pkl')
dl_18[dl_18['player'] == 'charlie morton'].loc[13]

player              charlie morton
posititon                       SP
team                            TB
injury                    Shoulder
days                            11
year                          2018
list                            10
startdate      2018-08-29 00:00:00
enddate                        9/8
moneyearned                 413974
Name: 13, dtype: object

In [64]:
# dl_18['startdate'] = dl_18['startdate'].str.strip()

In [71]:
# dl_18['startdate'] = dl_18['startdate'].str.replace('/','-')

In [92]:
# dl_18['startdate'][0] + '-' + str(dl_18['year'][0])

In [ ]:
# for idx, val in dl_18.iterrows():
#     dl_18['startdate'][idx] = dl_18['startdate'][idx] + '-' + str(dl_18['year'][idx])

In [ ]:
# dl_18['startdate'] = pd.to_datetime(dl_18['startdate'])

In [115]:
dl_18['startdate'] = pd.to_datetime(dl_18['startdate'], format="%Y/%m/%d")

In [116]:
dl_18

,player,posititon,team,injury,days,year,list,startdate,enddate,moneyearned
0,eric hanhold,P,NYM,Oblique,7,2018,60,2018-09-25,10/1,20510
1,michael fulmer,SP,DET,Knee/Oblique,47,2018,60,2018-09-21,10/110-day,145324
2,clay buchholz,SP,TOR,Elbow/Oblique,47,2018,60,2018-09-15,10/110-day,379055
3,luiz gohara,SP,ATL,Shoulder/Ankle,49,2018,60,2018-09-14,10/110-day,146216
4,michael kopech,SP,CHW,Elbow Tommy John,24,2018,60,2018-09-08,10/1,70320
5,keury mella,RP,CIN,Oblique,28,2018,60,2018-09-04,10/1,82040
6,joseph biagini,RP,TOR,Oblique,11,2018,10,2018-09-04,9/14,32230
7,jose mujica,P,TB,Undisclosed,29,2018,60,2018-09-03,10/1,84970
8,brock stewart,SP,LAD,Oblique,30,2018,60,2018-09-02,10/1,87900
9,pablo lopez,SP,MIA,Shoulder,31,2018,60,2018-09-01,10/1,90830
10,kendall graveman,SP,CHC,Elbow Tommy John,31,2018,60,2018-09-01,10/1,393328
11,robert stephenson,SP,CIN,Shoulder,33,2018,10,2018-08-30,10/1,98472
12,andrew miller,RP,STL,Shoulder/Knee,99,2018,10,2018-08-29,9/1060-day,4790313
13,charlie morton,SP,TB,Shoulder,11,2018,10,2018-08-29,9/8,413974
14,amir garrett,RP,CIN,Foot,13,2018,10,2018-08-29,9/10,38090
15,clayton richard,SP,TOR,Knee,35,2018,60,2018-08-28,10/1,564515
16,brett anderson,SP,OAK,Arm/Shoulder,68,2018,10,2018-08-28,9/1310-day,1166472
17,kelvin herrera,RP,CHW,Foot/Shoulder,50,2018,10,2018-08-27,10/110-day,2133750
18,marco gonzales,SP,SEA,Neck,16,2018,10,2018-08-27,9/11,47344
19,mike mayers,RP,STL,Shoulder,17,2018,10,2018-08-26,9/11,49810
20,sean manaea,SP,OAK,Shoulder,37,2018,10,2018-08-26,10/1,109409
21,daniel hudson,RP,LAA,Arm,49,2018,60,2018-08-25,10/110-day,143570
22,nick gardewine,P,TEX,Arm,38,2018,60,2018-08-25,10/1,111340
23,jarlin garcia,RP,MIA,Ankle,12,2018,10,2018-08-24,9/4,35808
24,bartolo colon,SP,TEX,Back,9,2018,10,2018-08-24,9/1,84681
25,elieser hernandez,RP,MIA,Finger/Teeth,55,2018,10,2018-08-24,9/410-day,322300
26,tyler chatwood,SP,CHC,Hip,12,2018,10,2018-08-23,9/3,806448
27,neil ramirez,RP,CLE,Back,11,2018,10,2018-08-23,9/2,32230
28,edubray ramos,RP,PHI,Finger/Knee/Shoulder,33,2018,10,2018-08-23,9/110-day,98274
29,aroldis chapman,RP,NYY,Knee,29,2018,10,2018-08-22,9/19,2338705
...,...,...,...,...,...,...,...,...,...,...
309,drew smyly,RP,TEX,Ulnar Nerve,187,2018,60,2018-03-29,10/1,3016123
310,gabriel ynoa,SP,BAL,Shin,187,2018,60,2018-03-29,10/1,552024
311,mark melancon,RP,SF,Arm,65,2018,60,2018-03-29,6/1,6989255
312,ryan merritt,RP,TB,Shoulder,107,2018,60,2018-03-29,7/13,313938
313,austin maddox,RP,BOS,Shoulder,187,2018,60,2018-03-29,10/1,547910
314,ronald herrera,RP,TEX,Shoulder,187,2018,60,2018-03-29,10/1,548845
315,brent honeywell,SP,TB,Elbow Tommy John,187,2018,60,2018-03-29,10/1,547910
316,ryan dull,RP,OAK,Shoulder,17,2018,10,2018-03-29,4/14,50728
317,tyler thornburg,RP,BOS,Shoulder,98,2018,10,2018-03-29,7/4,1080156
318,mark leiter,RP,TOR,Arm,49,2018,10,2018-03-29,5/16,144746
319,rafael montero,RP,TEX,Elbow,187,2018,60,2018-03-29,10/1,561000
320,brett graves,RP,MIA,Oblique,79,2018,60,2018-03-29,6/15,462940
321,jimmy nelson,SP,MIL,Shoulder,187,2018,60,2018-03-29,10/1,3719804
322,clayton blackburn,RP,CIN,Elbow,187,2018,60,2018-03-29,10/1,547910
323,michael fiers,SP,OAK,Back,11,2018,10,2018-03-29,4/8,354838
324,alex meyer,SP,LAA,Shoulder,187,2018,60,2018-03-29,10/1,554455
325,jerad eickhoff,SP,PHI,Shoulder,159,2018,60,2018-03-29,9/3,485586
326,joe ross,SP,WSH,Elbow Tommy John,160,2018,60,2018-03-29,9/4,488480
327,anthony desclafani,SP,CIN,Oblique,69,2018,60,2018-03-29,6/5,319056
328,carlos rodon,SP,CHW,Shoulder,73,2018,60,2018-03-29,6/9,902718
329,michael lorenzen,RP,CIN,Shoulder,56,2018,10,2018-03-29,5/23,395136
330,andrew heaney,SP,LAA,Elbow,16,2018,10,2018-03-29,4/13,68816
331,dan straily,SP,MIA,Elbow,33,2018,10,2018-03-29,4/30,598785
332,jharel cotton,SP,OAK,Elbow,187,2018,60,2018-03-29,10/1,552959
333,michael pineda,SP,MIN,Elbow Tommy John,187,2018,60,2018-03-29,10/1,2010811
334,jose de leon,RP,TB,Elbow Tommy John,187,2018,60,2018-03-29,10/1,548471
335,madison bumgarner,SP,SF,Finger,69,2018,60,2018-03-29,6/5,4451604
336,matthew strahm,RP,SD,Knee,40,2018,10,2018-03-29,5/7,118880
337,grant dayton,RP,ATL,Elbow Tommy John,187,2018,60,2018-03-29,10/1,568106
338,zack jones,RP,NYM,Shoulder,30,2018,7,2018-09-01,9/30,83190